---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-minio"
      include_role:
        name: "ansible-minio"

  vars:
    minio_install_server: false
    minio_install_client: true
