---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: minio-ubuntu-22.04-04
    image: ghcr.io/drgogeta86/dockerfiles-molecule/python-molecule:22.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
