---

- hosts: all
  any_errors_fatal: true
  gather_facts: true

  roles:
    - ansible-minio
  vars:
    minio_server_datadirs:
      - "/var/data/minio01"
      - "/var/data/minio02"
      - "/var/data/minio03"
      - "/var/data/minio04"
    minio_server_cluster_nodes:
      - "http://{{ ansible_hostname }}:9091/test1"
      - "http://{{ ansible_hostname }}:9091/test2"
      - "http://{{ ansible_hostname }}:9091/test3"
      - "http://{{ ansible_hostname }}:9091/test4"
